<div class="container">
    <div>Name: <?=$_POST["fname"]." ".$_POST["lname"]?></div>
    <div>Email: <?=$_POST["email"]?></div>
    <div>Phone Number: <?=$_POST["tel"]?></div>
    <br>
    <div><?="{$product['name']} - {$product['price']} CZK, {$_POST['count']} ks"?></div>
    <div style="border-bottom: solid 1px grey"><?="{$product['price']} * {$_POST['count']} = ".floatval($product['price'])* floatval($_POST['count'])." CZK"?></div>
    <br>
    <div>Final Price: <?=round(floatval($product['price'])* floatval($_POST['count'])*1.21, 2)." CZK"?><div class="currency" id="usd"></div></div>
    

</div>




<script>

var price = '<?php echo round(floatval($product['price'])* floatval($_POST['count'])*1.21, 2) ?>';

console.log(price);
fetch('https://data.kurzy.cz/json/meny/b[6].json')
  .then(response => response.text())
  .then(data => {
    document.getElementById("usd").innerHTML= "("+Math.round(price/JSON.parse(data).kurzy.USD.dev_stred*100)/100+" USD)";
  })
  .catch(error => {
    console.error('Chyba při získávání dat:', error);
  });

</script>



